---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jameslendrem.
--- DateTime: 17/01/2024 20:19
---

local pd <const> = playdate
local gfx <const> = pd.graphics;

local initVelocity = 5

class('Ball').extends(gfx.sprite)

function Ball:fixToBat(bat)
    self.bat = bat
end

function Ball:init(x, y)

    local ballSize = 4
    local ballImage = gfx.image.new(ballSize * 2, ballSize * 2)

    gfx.pushContext(ballImage)
        gfx.drawCircleAtPoint(ballSize, ballSize, ballSize)
    gfx.popContext();

    self:add()
    self:setImage(ballImage)

    self:setCollideRect(0, 0, self:getSize())
    self.speed = speed
    self:moveTo(x, y)
    self:add()

    self.bat = nil
    self.velocity = {
        0, initVelocity
    }

end

function Ball:moveWithBat()

    if (not self.bat) then
        return
    end

    local x, y = self.bat:getPosition()
    self:moveTo(x, y - 20)

    if (pd.buttonJustPressed(pd.kButtonA)) then
        self.bat = nil
    end

end

function Ball:moveBall()

    if (self.bat) then
        return
    end

    local newX = self.x + self.velocity[1]
    local newY = self.y + self.velocity[2]

    self:moveTo(newX, newY)

end

function Ball:update()

    self:moveWithBat()
    self:moveBall()


end