---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jameslendrem.
--- DateTime: 17/01/2024 20:28
---

local pd <const> = playdate
local gfx <const> = pd.graphics

local speed = 5

class("Bat").extends(gfx.sprite)

function Bat:init(x, y)

    local batWidth = 40
    local batHeight = 10
    local batImage = gfx.image.new(batWidth, batHeight)

    gfx.pushContext(batImage)
        gfx.drawRect(0, 0, batWidth, batHeight)
    gfx.popContext()

    self:setImage(batImage)

    self:setCollideRect(0, 0, batWidth, batHeight)
    self.speed = speed
    self:moveTo(x, y)
    self:add()

end

function Bat:checkForBallCollision()

    local actualX, actualY, collisions, total = self:checkCollisions(self.x, self.y);

    if (total == 0) then
        return false
    end

    local hasCollided = false

    if (total > 0) then
        for i, collision in pairs(collisions) do

            local collideObject = collision["other"]
            if (collideObject:isa(Ball)) then
                hasCollided = true
            end

        end
    end

    return hasCollided

end

function Bat:update()

    if (self:checkForBallCollision()) then
        print("Ball Collision")
    end

    --- just for testing
    if (pd.buttonIsPressed(pd.kButtonUp)) then
        self:moveBy(0, -speed)
    end

    if (pd.buttonIsPressed(pd.kButtonDown)) then
        self:moveBy(0, speed)
    end

    if (pd.buttonIsPressed(pd.kButtonLeft)) then
        self:moveBy(-speed, 0)
    end

    if (pd.buttonIsPressed(pd.kButtonRight)) then
        self:moveBy(speed, 0)
    end

end